### ISSUE TITLE
Remove mentions from the digest

### ISSUE THREAD

**Issue by damithc** [nus-oss/GithubDigest#34]
![image](https://github.com/nus-oss/GithubDigest/assets/1673303/e0beb07e-7946-418f-ab5d-b77a102f6226)

Shouldn't these be changed to @name -> `@name` from the digest posts? Otherwise these uses will get spammed from the digest posts.

**Comment by Eclipse-Dominator** [comment]
I think we can change all references' '@' symbol to use fullwidth commercial at ('＠') which will not trigger references.
e.g.
@damithc 
＠damithc

**Comment by damithc** [comment]
I prefer something that's not deceptive (and easy to debug), such as using backticks.

**Comment by Eclipse-Dominator** [comment]
I feel that it is much safer if we replace '@' with the fullwidth at sign.
Since fetched comments are not generated, it's possible to escape referencing if we just wrap backticks like so:

`a sample text @damithc text` => `a sample text `@damithc` text`

A foolproof solution will require identifying backtick wrappers which will lead to more complications as github supports wrapping with multiple backticks

**Comment by damithc** [comment]
> A foolproof solution will require identifying backtick wrappers which will lead to more complications as github supports wrapping with multiple backticks

I see your point. Let's use the fullwidth at sign.
